### ISSUE TITLE
freebayes failed to build on Mac OS X 10.10.1 

### ISSUE THREAD

**Issue by RodrigoGM** [chapmanb/homebrew-cbl#14]
I'm attempting to build freebayes on a mac in several occasions. The build fails due to the smithwaterman library, though I'm not sure exactly why.  When I attempt to install, the message below.
For more details I ran a ```brew gist-logs freebayes``` and it's located here https://gist.github.com/d748473463ac04ecc4b4

```
$brew install freebayes
...
==> cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/freebayes/0.9.14-15 -DCMAKE_BUILD_TYPE=None -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev
==> make
==> make
==> make
  * linking smithwaterman
ld: internal error: atom not found in symbolIndex(__ZNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6assignINS_16reverse_iteratorINS_11__wrap_iterIPcEEEEEENS_9enable_ifIXsr21__is_forward_iteratorIT_EE5valueERS5_E4typeESD_SD_) for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [smithwaterman] Error 1
make: *** [smithwaterman/SmithWatermanGotoh.o] Error 2

READ THIS: http://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/chapmanb/homebrew-cbl/issues
```

Any help is appreciated !
hope all is well,

Rodrigo

**Comment by roryk** [comment]
Closing this, @RodrigoGM. Feel free to reopen if it still isn't working for you. Hope everything is all set.

**Comment by RodrigoGM** [comment]
OK.  I have freebayes installed manually, but have not continued to try installing with brew lately.

Thanks for all the help
