### ISSUE TITLE
vep install fail running bcbio_nextgen_install.py 

### ISSUE THREAD

**Issue by dwaggott** [chapmanb/homebrew-cbl#17]
Might there be some dependencies I didn't install? 

command:
`python bcbio_nextgen_install.py ~/apps/bcbio --tooldir=~/apps --genomes GRCh37 --aligners bwa --aligners bowtie2`

problem:
```
dwaggott@sh-2-14: ~/apps
$ /home/dwaggott/apps/bin/brew install --env=inherit  vep
==> Installing vep from chapmanb/homebrew-cbl
==> Downloading https://github.com/Ensembl/ensembl-tools/archive/771dfa1016c357145be7016c91e1155ae7c021f2.zip
Already downloaded: /home/dwaggott/.cache/Homebrew/vep-75_2014-06-12.zip
==> Patching
==> export FTP_PASSIVE=1 && /share/PI/euan/apps/Cellar/vep/75_2014-06-12/INSTALL.pl -a a -d /share/PI/euan/apps/Cellar/vep/75_2014-06-12/lib -c /share/PI/euan/apps/Cellar/vep/75_2014-06-12/share/data
BEGIN failed--compilation aborted at /home/dwaggott/apps/lib/perl5/IPC/Cmd.pm line 58.
Compilation failed in require at /home/dwaggott/apps/lib/perl5/Archive/Extract.pm line 8.
BEGIN failed--compilation aborted at /home/dwaggott/apps/lib/perl5/Archive/Extract.pm line 8.
Compilation failed in require at /share/PI/euan/apps/Cellar/vep/75_2014-06-12/INSTALL.pl line 7.
BEGIN failed--compilation aborted at /share/PI/euan/apps/Cellar/vep/75_2014-06-12/INSTALL.pl line 7.

READ THIS: https://github.com/Homebrew/linuxbrew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/chapmanb/homebrew-cbl/issues
```

**Comment by chapmanb** [comment]
Daryl;
Sorry about the issues. This isn't the best standalone brew recipe since it does need a bunch of perl dependencies I'm not sure how exactly to do the homebrew way. In CloudBioLinux we install these upstream of brew, and here is the full list:

https://github.com/chapmanb/cloudbiolinux/blob/336c6dee3e24321878529e91f5c708a0e80c3c97/cloudbio/package/brew.py#L279

In this case I think you need `IPC::Cmd` with something like:
```
cpanm -i --notest 'IPC::Cmd'
```
Hope this helps get it installed.

**Comment by dwaggott** [comment]
K, I'll work through the dependencies and send an update.

p.s. A vote for incorporating RTG now that it has an academic licence and
ABRA as a polishing step.

**Comment by dwaggott** [comment]
A few others popped up:

Params::Check

Module::Load::Conditional

**Comment by chapmanb** [comment]
Daryl;
Thanks much for catching the additional packages. I added these to the list.

ABRA is still something we'd like to work on but haven't had time to do a full evaluation yet. The realigning callers like HaplotypeCaller and FreeBayes have improved indel calling quite a bit but it would be useful to determine if a pre-processing step helps.

What functionality do you like from the RTG tools that should be incorporated? We're involved with the GA4GH project and have been hoping to migrate to tools developed as part of that effort, so have been using bcbio.variation as a placeholder for validation work until then.

Thanks again.

**Comment by dwaggott** [comment]
Never enough time!

A few things I've liked about RTG are speed, sensitivity and notably the
pedigree caller.
