### ISSUE TITLE
vcflib - Error: htslib/bgzf.h: No such file or directory

### ISSUE THREAD

**Issue by tseemann** [chapmanb/homebrew-cbl#20]
I compiled this morning outside of brew ok, not sure what is going on here?

```
brew install vcflib
==> Installing vcflib from chapmanb/homebrew-cbl
==> Cloning https://github.com/ekg/vcflib.git

<snip>

Submodule path 'tabixpp/htslib': checked out 'f83dfd233af3459e3b638fcb6379beb4c67b7c10'
==> make
make[3]: Leaving directory `/tmp/vcflib-0DMkzs/tabixpp/htslib'
g++ -g -Wall -O2 -fPIC  -o tabix++ main.cpp tabix.o -Ihtslib -L. -Lhtslib -lhts -lpthread -lm -lz
make[2]: Leaving directory `/tmp/vcflib-0DMkzs/tabixpp'
make[1]: Leaving directory `/tmp/vcflib-0DMkzs/tabixpp'
g++ -c -o src/Variant.o src/Variant.cpp -I. -L. -Ltabixpp/ -lvcflib -ltabix -lz -lm -msse2 -O3 -D_FILE_OFFSET_BITS=64
In file included from src/Variant.h:18:0,
                 from src/Variant.cpp:1:
./tabixpp/tabix.hpp:4:25: fatal error: htslib/bgzf.h: No such file or directory
 #include "htslib/bgzf.h"
                         ^
compilation terminated.
make: *** [src/Variant.o] Error 1
```

**Comment by chapmanb** [comment]
Torsten;
Thanks much. Apologies, looks like something problematic happened with sub-modules and checking out the older version. I updated to the latest which seems to resolve the issue. Thanks again for the heads up.

**Comment by wrshoemaker** [comment]
I'm getting something similar when installing vcflib from brew. 
  
      brew install vcflib

....

      Resolving deltas: 100% (3865/3865), done.
      Checking connectivity... done.
      Submodule path 'tabixpp/htslib': checked out 'f83dfd233af3459e3b638fcb6379beb4c67b7c10'
      ==> make
          ar -t [-TLsv] archive [file ...]
          ar -x [-ouTLsv] archive [file ...]
      make[2]: *** [libtabix.a] Error 1
      make[1]: *** [all-recur] Error 1 
      make: *** [tabixpp/tabix.o] Error 2

**Comment by chapmanb** [comment]
Sorry about the problem. It looks like something is broken with your build but hard to tell from just this output. If you run in verbose mode:
```
brew install -v vcflib
```
it should provide more information about what is wrong. It looks from that error like something is incompatible with `ar` on your system. What type of machine are you running this on? Hope this helps some.

**Comment by tseemann** [comment]
I'm trying to get it into homebrew-science: https://github.com/Homebrew/homebrew-science/pull/2092

The make error is genuine, there is a bug in Erik's makefile: https://github.com/ekg/tabixpp/issues/5

**Comment by chapmanb** [comment]
Torsten;
Thanks much for digging into this. It sounds like this is an issue on Macs? Sorry, I'm ignorant about building there and most of these are tested only on Linux. If this gets into homebrew-science with your fixes happy to remove this formula in favor of that. Thanks again.

**Comment by wrshoemaker** [comment]
Thanks for the response. Sorry about the delay. I updated brew before installing vcflib. I'm running it on OSX Yosemite.  The verbose output is below. 

     make

     cd tabixpp && /Applications/Xcode.app/Contents/Developer/usr/bin/make
     ar -cru libtabix.a
     2015-04-24 17:11:59 -0400
     2015-04-24 17:11:59 -0400

     make

     cd tabixpp && /Applications/Xcode.app/Contents/Developer/usr/bin/make
     ar -cru libtabix.a
     2015-04-24 17:11:59 -0400

     make

     cd tabixpp && /Applications/Xcode.app/Contents/Developer/usr/bin/make
     ar -cru libtabix.a
     ar: no archive members specified

**Comment by tseemann** [comment]
@chapmanb I don't know much about building on Macs but i've been forced into it to get things into homebrew-science. I will inform you as they are accepted so you (and I) can remove them from our repositories.
