### ISSUE TITLE
sailfish-cbl formula name conflict

### ISSUE THREAD

**Issue by tseemann** [chapmanb/homebrew-cbl#26]
@roryk  In brew the filename needs to match the formula name?

You have `sailfish-cbl.rb` with `class Sailfish < Formula`. 
I think it should be `class SailfishCbl`.
This is causing conflicts with the `sailfish.rb` in `homebrew-science`.

**Comment by chapmanb** [comment]
Torsten;
Thanks for this heads up an this and sorry for the delay in fixing. I swapped over the naming to avoid any clashing issues. We definitely want to support the homebrew-science community recipes over our custom ones.
