### ISSUE TITLE
discovar now in homebrew-science

### ISSUE THREAD

**Issue by tseemann** [chapmanb/homebrew-cbl#27]
FYI - @sjackman got discovar in main homebrew-science

https://github.com/Homebrew/homebrew-science/blob/3dcad6295385493c5d3807578e6763bf27c762f7/discovar.rb

Should we delete from here?

**Comment by chapmanb** [comment]
Torsten -- thanks again for letting us know. I dropped the version in homebrew-cbl to avoid clashes.
