### ISSUE TITLE
publish vep recipe to homebrew-science

### ISSUE THREAD

**Issue by matthdsm** [chapmanb/homebrew-cbl#28]
Hi,

would it be possible to publish the recipe for VEP to homebrew science?

Thanks a lot!
M

**Comment by chapmanb** [comment]
Absolutely, feel free to update and port over the recipe to homebrew-science. We're very happy if anyone wants to take ownership of these. From our side we've focused our maintenance efforts on having an up to date VEP recipe in bioconda (https://github.com/bioconda/bioconda-recipes) so won't be actively doing more work on these, but would love if others want to build off the recipes. Thanks much.
