### ISSUE TITLE
freebayes/vcflib: `tabix.hpp: No such file or directory`

### ISSUE THREAD

**Issue by stephenturner** [chapmanb/homebrew-cbl#29]
First, thanks for the enormous effort and time you spend on this. Truly awesome to the community. 

I'm trying to build @tseemann nullarbor on a fresh Ubuntu 14.04 instance on AWS, and I'm _almost_ there. I've got most of nullarbor's dependencies, except for @ekg freebayes. This is the installation script I'm using:

<https://gist.github.com/stephenturner/005d4e4e322b8cf5b991d1d357527859>

When I try to `brew install freebayes`, I run into the following error:

```
Submodule path 'vcflib/tabixpp/htslib': checked out '0f298ce22c5c825c506129bf242348a31630c382'
==> Checking out revision 7dd41db
==> Checking out revision 7dd41db
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/home/
==> make
==> make autoversion
==> make
Last 15 lines from /home/ubuntu/.cache/Homebrew/Logs/freebayes/04.make:
wget -q http://hypervolu.me/freebayes/build/v0.9.21-7-g7dd41db-dirty &
cd src && make
make[1]: Entering directory '/tmp/freebayes-20160616-5455-1tfez8i/src'
DETECTED_VERSION = v0.9.21-7-g7dd41db-dirty
CURRENT_VERSION  = v0.9.21-7-g7dd41db-dirty
g++ -O3 -D_FILE_OFFSET_BITS=64 -g -I../bamtools/src -I../ttmath -I../vcflib/src -I../vcflib/ -c freebayes.cpp
In file included from AlleleParser.h:31:0,
                 from freebayes.cpp:27:
../vcflib/src/Variant.h:18:21: fatal error: tabix.hpp: No such file or directory
 #include "tabix.hpp"
                     ^
compilation terminated.
make[1]: *** [Makefile:107: freebayes.o] Error 1
make[1]: Leaving directory '/tmp/freebayes-20160616-5455-1tfez8i/src'
make: *** [Makefile:2: all] Error 2
```

Not sure how to handle this one. I should also say that I have no problem installing freebayes 1.x outside of homebrew:

```bash
git clone --recursive git://github.com/ekg/freebayes.git
cd freebayes
make
```

**Comment by chapmanb** [comment]
Stephen;
Sorry about the problem. These formula are getting out of date and starting to bitrot. I believe @tseemann has been working on getting FreeBayes into homebrew-science so if you want to use homebrew that might be the best place to start (https://github.com/Homebrew/homebrew-science/pull/3287).

I've moved most of my packaging efforts to bioconda (https://bioconda.github.io/). If that is an installation option for you there are up to date FreeBayes builds for Linux (and OSX) ready to go there.

Hope one of those options works for you.

**Comment by yzhzu** [comment]
==> Checking out revision 7dd41db
==> Checking out revision 7dd41db
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/home/rcmm/.linuxbrew/Cellar/freebayes/0.9.21-7 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -D
==> make
==> make autoversion
==> make
Last 15 lines from /home/rcmm/.cache/Homebrew/Logs/freebayes/04.make:
wget -q http://hypervolu.me/freebayes/build/v0.9.21-7-g7dd41db-dirty &
cd src && make
make[1]: Entering directory “/tmp/freebayes-20160814-716-hlrwu4/src”
DETECTED_VERSION = v0.9.21-7-g7dd41db-dirty
CURRENT_VERSION  = v0.9.21-7-g7dd41db-dirty
g++ -O3 -D_FILE_OFFSET_BITS=64 -g -I../bamtools/src -I../ttmath -I../vcflib/src -I../vcflib/ -c freebayes.cpp
In file included from AlleleParser.h:31:0,
                 from freebayes.cpp:27:
../vcflib/src/Variant.h:18:21:fatal error: tabix.hpp: No such file or directory
 #include "tabix.hpp"
                     ^
compilation terminated.
make[1]: *** [freebayes.o] error 1
make[1]: Leaving directory “/tmp/freebayes-20160814-716-hlrwu4/src”
make: *** [all] error 2

now I met the same problem. can someone help me solve this error. thanks very much

**Comment by tseemann** [comment]
@yzhzu freebayes is not part of homebrew-science 

https://github.com/Homebrew/homebrew-science/blob/master/freebayes.rb

**Comment by chapmanb** [comment]
Torsten and Shaun -- thanks so much for getting this pushed into homebrew-science. Brilliant to have it properly maintained and not have my version messing everyone up.

**Comment by tseemann** [comment]
@chapmanb I've removed it from this repo (and my repo too!)

**Comment by chapmanb** [comment]
Thanks Torsten, I was going to do that this morning when I realized you already beat me to it. Thanks for being so on top of this.
